name: '💫 Definition of done'
description: '💫 Standard ticket when we finish up a project'
assignees: 'levdbas'
title: '💫 Definition of done'
labels:
  - 'project management'

body:
  - type: markdown
    attributes:
      value: >
        **These are the most common tasks that we have in each project.**
        Please check the ones that apply to this project.


  - type: checkboxes
    attributes:
      label: Tasks at start of project
      description: Initial tasks to be completed before starting the project
      options:
        - label: item 1
        - label: item 2
  - type: checkboxes
    attributes:
      label: Tasks during project
      description: Common tasks to be completed during the project
      options:
        - label: item 1
        - label: item 2
  - type: checkboxes
    attributes:
      label: Tasks at end of project
      description: Final tasks to be completed before finishing the project
      options:
        - label: item 1
        - label: item 2