name: '💫 Definition of done'
description: '💫 Standard ticket when we finish up a project'
assignees: 'levdbas'
title: '💫 Definition of done'
labels:
  - 'project management'

body:
  - type: markdown
    attributes:
      value: >
        **These are the most common tasks that we have in each project.**
        Please check the ones that apply to this project.


  - type: checkboxes
    attributes:
      label: Tasks at start of project
      description: Initial tasks to be completed before starting the project
      options:
        - label: Do we have a hosting environment?
        - label: Do we have a domain name?
        - label: Will we do maintenance on the project?
  - type: checkboxes
    attributes:
      label: Tasks during project
      description: Common tasks to be completed during the project
      options:
        - label: 'Bigger projects: do we have staging backups in place?'
  - type: checkboxes
    attributes:
      label: Tasks at end of project
      description: Final tasks to be completed before finishing the project
      options:
        - label: Are forms working/do they send replies?
        - label: Is ReCaptcha set up?
        - label: Is Mailgun set up?
        - label: Check SMTP settings
        - label: Add website to Google Analytics
        - label: Configure tracking/analytics
        - label: Add website to Google Search Console
        - label: Did we enable caching? Did we set the caching to 10 hours max?
        - label: Did we configured backups?
        - label: is the .env file set to production?
        - label: Did we add the website to ManageWP?
