name: '🎆 Project lifecycle - Definition of done'
description: Standard ticket when we finish up a project
title: '🎆 Project lifecycle - Definition of done'
labels: ''

body:
  - type: markdown
    attributes:
      value: >
        **This ticket is to track the most important and common tasks within each project lifecycle.**